project:
  type: website
  title: "causal_bounds_smoking_example"
  output-dir: _site
  resources:
    - fonts
    - causal_mediation_tar.png

website:
  site-url: https://causalbounds-puremediators.netlify.app

brand: _brand.yml

format:
  revealjs:
    theme: [default, custom-fonts.scss]
    transition: none
    background-transition: none
    pdf-separate-fragments: false
    lang: en
    auto-stretch: true